### ISSUE TITLE
Создать функционал авторизации и регистрации

### ISSUE THREAD

**Issue by nurlansapyzhan** [nurlansapyzhan/marketplace#1]
### Для чего это нужно?
Для дальнейшей работы с авторизированными и зарегистрированными пользователями

### Как это сделать?
Установить FastAPI Users используя pip.
Используя документацию FastAPI Users выбрать подходящие транспорты и стратегии. Установить asyncpg для работы с FastAPI Users. В отдельной директории создаем файлы database.py, auth.py,  manager.py и schemas.py. 
В файле database.py будет находиться путь к базе данных, данные которой будут лежать в отдельном файле для безопасности. Там же прописываем класс User для создания таблички в базе данных. 
С помощью alembic создаем миграции для базы данных. 
В файл auth.py добавляем выбранный нами транспорт и стратегию из документации FastAPI Users. 
Из документации FastAPI Users в файл manager.py вставляем код для создания менеджера. Редактируем этот код оставляя только нужное нам. 
В файл schemas.py так же вставляем код из документации FastAPI Users меняя его под себя и прописываем наши поля и типы данных для пользователя.
В файл main.py добавляем роутеры из документации FastAPI Users. 
Последним этапом будет создания инстанса fastapi_users.

### Критерии приёмки:
Создается пользователь в базе данных, имеет возможность входа и выхода через сваггер

### Планируемое время работы:
5 часов

### Фактически затраченное время:
5 часов

**Comment by AlibekBeket** [comment]
Всем критериям соответствует
